// these are all generated by ChatGPT

export const weatherQuotes = {
    hot: [
        "It's so hot the sun applied for overtime.",
        "Hydrate or evaporate.",
        "Perfect weather to fry an egg on the sidewalk.",
        "The sun is feeling a little extra today."
    ],

    warm: [
        "A perfect day for sunglasses and bad decisions.",
        "Sun's out, vibes out.",
        "Great weather to touch grass.",
        "Nature said: go outside."
    ],

    cold: [
        "Time to dress like a burrito.",
        "If you can feel your toes, it's not cold enough.",
        "Perfect weather for dramatic coat swishes.",
        "Cold enough to reconsider your life choices."
    ],

    freezing: [
        "It's colder than your ex's heart.",
        "Your breath now has special effects.",
        "Penguins would call this mild.",
        "Welcome to the ice age."
    ],

    rainy: [
        "Umbrella recommended. Or just embrace chaos.",
        "Rain today. Frogs tomorrow.",
        "Nature's car wash is running.",
        "The clouds are feeling emotional today."
    ],

    snowy: [
        "Snowball fights are legally encouraged.",
        "Somewhere a snowman is being born.",
        "Time to walk like a penguin.",
        "Winter wonderland unlocked."
    ]
};