// these are all generated by ChatGPT

export const weatherQuotes = {

    hot: [
        "It's so hot the sun applied for overtime.",
        "Hydrate or evaporate.",
        "Perfect weather to fry an egg on the sidewalk.",
        "The sun is feeling a little extra today.",
        "Air conditioning appreciation day.",
        "The pavement is plotting revenge.",
        "Shade is the real MVP today.",
        "Welcome to soup weather."
    ],

    warm: [
        "A perfect day for sunglasses and bad decisions.",
        "Sun's out, vibes out.",
        "Great weather to touch grass.",
        "Nature said: go outside.",
        "An excellent day for a long walk.",
        "The weather understood the assignment.",
        "Open a window and pretend you're productive.",
        "Just warm enough to make you optimistic."
    ],

    cool: [
        "A light jacket kind of day.",
        "Perfect weather for coffee outside.",
        "The air has main character energy today.",
        "A gentle reminder that fall exists.",
        "Sweater weather is knocking.",
        "Cool breeze, clear mind.",
        "The weather is quietly showing off.",
        "Ideal temperature for dramatic staring out windows."
    ],

    cold: [
        "Time to dress like a burrito.",
        "If you can feel your toes, it's not cold enough.",
        "Perfect weather for dramatic coat swishes.",
        "Cold enough to reconsider your life choices.",
        "Your nose knows it's cold.",
        "Layers are your personality today.",
        "Winter is rehearsing.",
        "A great day to stay inside and judge the weather."
    ],

    freezing: [
        "It's colder than your ex's heart.",
        "Your breath now has special effects.",
        "Penguins would call this mild.",
        "Welcome to the ice age.",
        "The air hurts your face.",
        "Everything outside is crunchy now.",
        "Winter has fully loaded.",
        "Even the wind is shivering."
    ],

    drizzle: [
        "Just enough rain to ruin a good hair day.",
        "A light sprinkle for dramatic effect.",
        "The sky is gently misting today.",
        "Barely rain, but your umbrella noticed.",
        "A polite drizzle has entered the chat.",
        "Just enough rain to question your outfit choices.",
        "The clouds are whispering today.",
        "A little rain never hurt anyone. Probably."
    ],

    heavyRain: [
        "Umbrella recommended. Or just embrace chaos.",
        "Rain today. Frogs tomorrow.",
        "Nature's car wash is running.",
        "The clouds are feeling emotional today.",
        "Puddle-jumping conditions detected.",
        "A cozy indoor day has been authorized.",
        "The sky forgot to turn off the faucet.",
        "Rain: the original white noise machine."
    ],

    snowy: [
        "Snowball fights are legally encouraged.",
        "Somewhere a snowman is being born.",
        "Time to walk like a penguin.",
        "Winter wonderland unlocked.",
        "Every surface is now a slip hazard.",
        "The world just hit the snooze button.",
        "Fresh snow: nature's reset button.",
        "Somewhere a sled is excited."
    ]
};